USE bel_pms;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS stream VARCHAR(100) DEFAULT NULL AFTER role,
    ADD COLUMN IF NOT EXISTS telephone VARCHAR(30) DEFAULT NULL AFTER stream,
    ADD COLUMN IF NOT EXISTS user_group VARCHAR(100) DEFAULT NULL AFTER telephone;
